{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "canopy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "canopy.labels" . | nindent 4 }}
  {{- include "canopy.annotations" (dict "ctx" . "specific" .Values.serviceAccount.annotations) | nindent 2 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
